name: Cypress Test
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

   basic-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: ./
        with:
          working-directory: cypress/e2e
          build: npx cypress run


